files = ['preload.cc', 'dlock.c', 'util.c', 'position.cc', 'template.cc', 'mutex.cc', 'thread.cc', 'detection.cc', 'avoidance.cc', 'graph.cc', 'Dimmunix.cc']

env = Environment(CCFLAGS='-Wall -g -DNDEBUG -D_GNU_SOURCE', LIBS=['pthread', 'dl', 'stdc++'])
env.SharedLibrary('dimmunix', files)
